<a href="https://colab.research.google.com/github/satyenncodes/packageprediction-linear_regression/blob/main/package_pridictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [1]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profilre_score','lpa'])
df

,cgpa,profilre_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from tensorflow.keras.layers import Dense, Input

In [ ]:
model = Sequential()
model.add(Input(shape=(2,)))
model.add(Dense(2, activation='linear'))
model.add(Dense(1, activation='linear'))

In [ ]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-0.33185   ,  1.1240793 ],
        [ 0.09072268,  0.76011693]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0084375],
        [-0.9625329]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=200,verbose=1,batch_size=1)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 86.1121 
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 83.7567 
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 81.3776 
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 79.0882 
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 76.8044 
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 74.5737 
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 72.4340 
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 70.3035 
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 68.1791
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 66.1670 
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 64.1541 
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 62.1895 
Epoch 13/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 60.2943 
Epoch 14/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 58.4027 
Epoch 15/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 56.6134 
Epoc

In [ ]:
model.get_weights()

[array([[0.12736155, 0.7668291 ],
        [0.54516566, 0.40603217]], dtype=float32),
 array([ 0.46292746, -0.3603885 ], dtype=float32),
 array([[ 1.5593019 ],
        [-0.60962474]], dtype=float32),
 array([0.40922374], dtype=float32)]

In [ ]:
new_data = np.array([[6,6]])

prediction = model.predict(new_data)

print("Predicted LPA:", prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Predicted LPA: 3.3527753
